### PR TITLE
Manushifva update

### PR DESCRIPTION
**Pull request by manushifva**
I've add the dark theme and fix some wrong file location.

Signed-off-by: manushifva mytrojan003@gmail.com

### CODE REVIEW

**Comment by ammarfaizi2** [comment]
Please read the following guidelines:
https://t.me/GNUWeebTDD/2630

Your PR isn't eligible to be merged at the moment.

**Comment by manushifva** [comment]
@ammarfaizi2 Why my PR can't be merged?

**Comment by ammarfaizi2** [comment]
Because you don't follow the requirements.

- You need a `Signed-off-by` sign for each commit.
- Commit in pull request MUST contain real person with a real email address.

Again, the reason for that is that the way the GitHub web interface work, those commits are invariably pure crap. Commits done
on GitHub invariably have totally unreadable descriptions, and often with anonymous email and no sign-offs etc that we require for PR submissions.

**Comment by ammarfaizi2** [comment]
@manushifva please see the following pull request example
https://github.com/GNUWeeb/GNUWeebBot/pull/37

Also, please read the guidelines and apply these guidelines to your commits:
https://t.me/GNUWeebTDD/2630

**Review by ammarfaizi2 — CHANGES_REQUESTED** [review]
Please read the PR guidelines on Telegram group.

**Pull request closed without merging**
