### PR TITLE
Update home.php

### PR DESCRIPTION
**Pull request by manushifva**

### CODE REVIEW

**Comment by Sprtcrnbry** [comment]
I would rather have all the extra resources go to our server than using a CDN. I will give more opinions after i check out the commits.
cc: @ammarfaizi2 for GPG signing compliance

**Review by ammarfaizi2 — CHANGES_REQUESTED** [review]
Thanks for contributing to GNU/Weeb.

Please read the following guidelines and submit a revision for this PR:
https://t.me/GNUWeebTDD/2630

After the basic requirements are satisfied, we can continue to code review step.

**Comment by ammarfaizi2** [comment]
> I would rather have all the extra resources go to our server than using a CDN

I don't like CDN contents as well. @manushifva please make those assets local.

**Comment by ammarfaizi2** [comment]
@Sprtcrnbry his commits have been signed with GPG. But missing `Signed-off-by`.

**Comment by manushifva** [comment]
> > I would rather have all the extra resources go to our server than using a CDN
> 
> I don't like CDN contents as well. @manushifva please make those assets local.
Thanks for the suggestion.
I will clone the file and add it to the asset. I also remove some unused CDN file.

**Review by Sprtcrnbry — CHANGES_REQUESTED** [review]
Can you make the page the same color scheme as the other pages?

**Comment by ammarfaizi2** [comment]
I refuse to pull complicated commits that have been made with the GitHub web. Especially with random email like this:
```
commit 582a1aa6ec60b30e33dfae242601865053952884 (HEAD -> manushifva-update, manushifva/manushifva-update)
Author: manushifva <60773626+manushifva@users.noreply.github.com>
Date:   Sat Jun 19 16:00:15 2021 +0700

    Change CDN to local copy

commit d2aa55e648f2a85c9ed56db3b3a56bd94cd9bfba
Author: manushifva <60773626+manushifva@users.noreply.github.com>
Date:   Sat Jun 19 15:58:03 2021 +0700

    Add local version of CDN

commit ec1d48061c8106351f100465bf8579bf0f3e82e4
Author: manushifva <60773626+manushifva@users.noreply.github.com>
Date:   Sat Jun 19 15:56:32 2021 +0700

    Add local version of CDN

commit 37be51d3fd8bdb37b7d919c75770d3b8837db680
Merge: ee14f5f ebdffd1
Author: manushifva <60773626+manushifva@users.noreply.github.com>
Date:   Sat Jun 19 14:14:14 2021 +0700

    Merge pull request #1 from manushifva/manushiva-patch-1
    
    Restyle home.php

commit ebdffd1c72cee514fca93dc63836446dd5e1c2d2
Author: manushifva <60773626+manushifva@users.noreply.github.com>
Date:   Sat Jun 19 14:12:21 2021 +0700

    Restyle home.php
    
    Note: some bug with smaller device view.
```

You are allowed to commit via GitHub web, but if your email is random, I will not pull.

Please also use `Signed-off-by` sign for each commit.

**Comment by manushifva** [comment]
@Sprtcrnbry yeah, but i think i will give the ligth theme option.

**Comment by ammarfaizi2** [comment]
I am closing this, let's go with single PR.

**Pull request closed without merging**
